name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*' # 推荐使用更精确的匹配，例如 v*.*.*

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    # VVVVVV  在这里添加权限声明  VVVVVV
    permissions:
      contents: write
    # ^^^^^^  这是解决问题的关键  ^^^^^^

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # 假设你有一个 npm script 来执行发布
      # 例如在 package.json -> "scripts": { "publish": "electron-forge publish" }
      - name: Publish to GitHub Releases
        run: npm run publish
        env:
          # GITHUB_TOKEN 是 electron-forge 自动寻找的环境变量
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}